<?php 
	function cabecera() {
		echo '
        	<div class="contenedor">
            <div class="encabezado">
            <a href="index.php"><h1 class="icon-hospital">Hospital Arcángeles</h1>
            </div></a>
            <a href="index.php"><input type="checkbox" id="menu-bar">
            <label class="icon-menu-outline" for="menu-bar"></label></a>
            <nav class="menu">
                <a href="index.php">Inicio</a>
                <a href="Paginas/Nosotros.php">Nosotros</a>
                <a href="Paginas/Contacto.php">Contacto</a>
                <a href="Paginas/Departamentos.php">Departamentos</a>
                <a href="Paginas/Citas.php">Citas</a>
            </nav>
       		</div>
		';
	}
	function subcabecera() {
		echo '
        	<div class="contenedor">
            <div class="encabezado">
            <a href="../index.php"><h1 class="icon-hospital">Hospital Arcángeles</h1>
            </div></a>
            <input type="checkbox" id="menu-bar">
            <label class="icon-menu-outline" for="menu-bar"></label>
            <nav class="menu">
                <a href="../index.php">Inicio</a>
                <a href="Nosotros.php">Nosotros</a>
                <a href="Contacto.php">Contacto</a>
                <a href="Departamentos.php">Departamentos</a>
                <a href="Citas.php">Citas</a>
            </nav>
       		</div>
		';
	}    
    function pie() {
        echo '
          <div class="contenedor">
              <p class="copy">Hospital Arcángeles &copy; 2019</p>
              <hr><br>
              <div class="sociales">
                  <a class="icon-gplus-squared" chref=""></a>
                  <a class="icon-linkedin-1"href=""></a>
                  <a class="icon-mail-alt" href=""></a>
                  <a class="icon-twitter-squared" href=""></a>
              <div>
        ';
    }

?>